name: Continuous Integration
on: [pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ job.status == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'issue_comment' && format('refs/pull/{0}/merge', github.event.issue.number) || '' }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/cache@v4
        name: Setup bun cache
        with:
          path: ~/.bun/install/cache
          key: "${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}"
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Project Dependencies
        run: bun install

      - name: Execute Unit tests
        run: bun run test